### ISSUE TITLE
Raise error when unauthorized

### ISSUE THREAD

**Issue by technicalpickles** [technicalpickles/pager_duty-connection#17]
https://github.com/technicalpickles/pager_duty-connection/issues/16 is a case where an unexpected nil happened, causing an error. The underlying problem was an incorrect token.

It should be possible to check for a 401 status code and raise a better error message similar to we do for 404. Details:
- https://github.com/technicalpickles/pager_duty-connection/blob/master/lib/pager_duty/connection.rb#L19-L28
- https://github.com/technicalpickles/pager_duty-connection/blob/master/lib/pager_duty/connection.rb#L143

That said, I'm kind of surprised that https://github.com/technicalpickles/pager_duty-connection/blob/master/lib/pager_duty/connection.rb#L30-L46 didn't cover this.

cc @huskercane

**Comment by aristocrates** [comment]
> That said, I'm kind of surprised that https://github.com/technicalpickles/pager_duty-connection/blob/master/lib/pager_duty/connection.rb#L30-L46 didn't cover this.

This is happening because the middleware executes in reverse order it is passed to `conn.use`, so if time parsing middleware raises on the body (which happens in this case when the response code is 401), `RaiseApiErrorOnNon200` never runs.

https://github.com/technicalpickles/pager_duty-connection/pull/30 would move response code handling middleware to the end of the block to ensure it executes first.

**Comment by bobbytables** [comment]
Thanks for posting this @aristocrates, saved me from a lengthy investigation.
